#!/bin/bash
#    Organic Photovoltaic Device Model - a drift diffusion base/Shockley-Read-Hall
#    model for organic solar cells. 
#    Copyright (C) 2012 Roderick C. I. MacKenzie
#
#	roderick.mackenzie@nottingham.ac.uk
#	www.roderickmackenzie.eu
#	Room B86 Coats, University Park, Nottingham, NG7 2RD, UK
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
if [ "$1" != "" ]
then
	if [ $1 == "--help" ]; then
	echo "opvdm_import - imports a saved opvdm simulation to the current directory,"
	echo "while checking for compatibility between input files."
	echo "Copyright Roderick MacKenzie 2012, released under GPLv2"
	echo ""
	echo "Usage: opvdm_import [options] [FILE]..."
	echo "FILE should be a directory containing the set of simulation files to be imported"
	echo ""
	echo "Options:"
	echo ""
	echo "	--help		displays the help"
	echo "	--version	displays the current version"
	echo ""
	echo "Additional information about opvdm is available at http://www.opvdm.com."
	echo ""
	echo "Report bugs to: roderick.mackenzie@nottingham.ac.uk"
	exit
	fi

	if [ $1 == "--version" ]; then
	echo "opvdm_import, Version 1.0"
	echo "Copyright and written by Roderick MacKenzie 2012, Released under GPLv2"
	echo ""
	echo "This is free software; see the source code for copying conditions."
	echo "There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or"
	echo "FITNESS FOR A PARTICULAR PURPOSE."
	exit
	fi
fi
for i in sim.inp device.inp stark.inp shg.inp dos0.inp jv.inp celiv.inp device_epitaxy.inp optics_epitaxy.inp optics.inp math.inp fit.inp dump.inp dump_time.inp light.inp tpv.inp otrace.inp server.inp; do
import_file=$1$i

if [ ! -f $i ]
then
    cp $import_file $i
else

	localver=`tail -n2 $i| sed 2d`
	importver=`tail -n2 $import_file| sed 2d`
	if [ "$localver" == "$importver" ]
	then
		echo cp $import_file $i
		cp $import_file $i
	else
		echo "No ver match for " $i "suggest: kdiff3 "$import_file $i
		#if [ "$2" == "--gui" ]
		#then
		#kdiff3 $import_file $i
		#else
		#diff $import_file $i
		#fi
	fi
fi
done

cp $1/doslayers.inp ./
cp $1/dump_time.inp ./
cp $1/thermal.inp ./
cp $1/ver.inp ./
